4	2	src/main/java/com/orb/battambang/doctor/RecordsViewController.java
5	5	src/main/java/com/orb/battambang/login/LoginPageController.java
17	17	src/main/resources/com/orb/battambang/checkup-menu.fxml
19	19	src/main/resources/com/orb/battambang/dental.fxml
96	89	src/main/resources/com/orb/battambang/doctor-consult.fxml
162	0	src/main/resources/com/orb/battambang/education-station.fxml
18	18	src/main/resources/com/orb/battambang/head-lice.fxml
19	19	src/main/resources/com/orb/battambang/hearing-test.fxml
19	19	src/main/resources/com/orb/battambang/height-and-weight.fxml
47	26	src/main/resources/com/orb/battambang/history-records.fxml
19	19	src/main/resources/com/orb/battambang/history.fxml
4	4	src/main/resources/com/orb/battambang/login-page.fxml
96	78	src/main/resources/com/orb/battambang/medicine-dispense.fxml
5	5	src/main/resources/com/orb/battambang/new-user.fxml
11	9	src/main/resources/com/orb/battambang/patient-filter.fxml
14	12	src/main/resources/com/orb/battambang/patient-registration.fxml
10	6	src/main/resources/com/orb/battambang/patient-search.fxml
2	2	src/main/resources/com/orb/battambang/records-view.fxml
19	19	src/main/resources/com/orb/battambang/snellens-test.fxml
-	-	src/main/resources/databases/clinicdb.db
1	1	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
0	117	src/main/java/com/orb/battambang/checkupstation/DentalController.java
0	117	src/main/java/com/orb/battambang/checkupstation/HeadLiceController.java
0	118	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
0	118	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
2	118	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
0	118	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
112	2	src/main/java/com/orb/battambang/doctor/DoctorConsultController.java
331	0	src/main/java/com/orb/battambang/education/EducationController.java
19	0	src/main/java/com/orb/battambang/login/LoginPageController.java
1	1	src/main/java/com/orb/battambang/login/NewUserController.java
1	0	src/main/java/com/orb/battambang/reception/PatientRegistrationController.java
1	0	src/main/java/module-info.java
6	6	src/main/resources/com/orb/battambang/edit-history.fxml
3	3	src/main/resources/com/orb/battambang/history-records.fxml
2	2	src/main/resources/com/orb/battambang/history.fxml
-	-	src/main/resources/databases/clinicdb.db
22	0	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
69	1	src/main/java/com/orb/battambang/doctor/DoctorConsultController.java
77	0	src/main/java/com/orb/battambang/doctor/HistoryRecordsController.java
204	0	src/main/java/com/orb/battambang/doctor/RecordsViewController.java
38	10	src/main/resources/com/orb/battambang/doctor-consult.fxml
45	0	src/main/resources/com/orb/battambang/history-records.fxml
2	1	src/main/resources/com/orb/battambang/history.fxml
14	0	src/main/resources/com/orb/battambang/records-view.fxml
-	-	src/main/resources/databases/clinicdb.db
4	4	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
14	11	src/main/java/com/orb/battambang/checkupstation/DentalController.java
19	16	src/main/java/com/orb/battambang/checkupstation/HeadLiceController.java
19	16	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
17	13	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
19	15	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
190	11	src/main/java/com/orb/battambang/doctor/DoctorConsultController.java
1	1	src/main/java/com/orb/battambang/login/LoginPageController.java
7	2	src/main/java/com/orb/battambang/util/Rectangles.java
65	95	src/main/resources/com/orb/battambang/doctor-consult.fxml
-	-	src/main/resources/databases/clinicdb.db
190	2	src/main/java/com/orb/battambang/doctor/DoctorConsultController.java
14	0	src/main/java/com/orb/battambang/util/Rectangles.java
329	9	src/main/resources/com/orb/battambang/doctor-consult.fxml
-	-	src/main/resources/databases/clinicdb.db
2	3	src/main/java/com/orb/battambang/reception/PatientRegistrationController.java
36	1	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
306	0	src/main/java/com/orb/battambang/checkupstation/DentalController.java
330	0	src/main/java/com/orb/battambang/checkupstation/HeadLiceController.java
0	55	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
0	54	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
0	54	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
0	55	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
2	2	src/main/java/com/orb/battambang/login/LoginPageController.java
11	2	src/main/java/com/orb/battambang/reception/Patient.java
171	0	src/main/java/com/orb/battambang/reception/PatientFilterController.java
142	51	src/main/java/com/orb/battambang/reception/PatientRegistrationController.java
2	1	src/main/java/com/orb/battambang/reception/PatientSearchController.java
4	4	src/main/java/com/orb/battambang/util/Rectangles.java
64	0	src/main/java/com/orb/battambang/util/TableViewUpdater.java
13	13	src/main/resources/com/orb/battambang/checkup-menu.fxml
207	0	src/main/resources/com/orb/battambang/dental.fxml
211	0	src/main/resources/com/orb/battambang/head-lice.fxml
11	11	src/main/resources/com/orb/battambang/hearing-test.fxml
13	13	src/main/resources/com/orb/battambang/height-and-weight.fxml
11	11	src/main/resources/com/orb/battambang/history.fxml
70	0	src/main/resources/com/orb/battambang/patient-filter.fxml
64	54	src/main/resources/com/orb/battambang/patient-registration.fxml
12	12	src/main/resources/com/orb/battambang/snellens-test.fxml
2	2	src/main/resources/com/orb/battambang/styles.css
-	-	src/main/resources/databases/clinicdb.db
134	5	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
154	6	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
160	11	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
134	9	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
134	9	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
1	1	src/main/java/com/orb/battambang/connection/DatabaseConnection.java
14	5	src/main/java/com/orb/battambang/reception/PatientRegistrationController.java
21	0	src/main/java/com/orb/battambang/util/CenteredListCell.java
10	0	src/main/java/com/orb/battambang/util/Labels.java
53	0	src/main/java/com/orb/battambang/util/QueueManager.java
1	1	src/main/java/com/orb/battambang/util/Rectangles.java
54	22	src/main/resources/com/orb/battambang/checkup-menu.fxml
65	31	src/main/resources/com/orb/battambang/hearing-test.fxml
72	38	src/main/resources/com/orb/battambang/height-and-weight.fxml
101	68	src/main/resources/com/orb/battambang/history.fxml
70	36	src/main/resources/com/orb/battambang/snellens-test.fxml
23	0	src/main/resources/com/orb/battambang/styles.css
-	-	src/main/resources/databases/clinicdb.db
24	11	src/main/resources/com/orb/battambang/checkup-menu.fxml
24	10	src/main/resources/com/orb/battambang/hearing-test.fxml
24	10	src/main/resources/com/orb/battambang/height-and-weight.fxml
55	41	src/main/resources/com/orb/battambang/history.fxml
24	10	src/main/resources/com/orb/battambang/snellens-test.fxml
20	50	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
27	50	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
40	55	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
28	52	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
28	50	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
1	1	src/main/java/com/orb/battambang/login/LoginPageController.java
7	1	src/main/java/com/orb/battambang/reception/PatientRegistrationController.java
21	0	src/main/java/com/orb/battambang/util/Rectangles.java
3	3	src/main/resources/com/orb/battambang/checkup-menu.fxml
3	3	src/main/resources/com/orb/battambang/hearing-test.fxml
7	7	src/main/resources/com/orb/battambang/height-and-weight.fxml
3	3	src/main/resources/com/orb/battambang/history.fxml
3	3	src/main/resources/com/orb/battambang/snellens-test.fxml
-	-	src/main/resources/databases/clinicdb.db
32	6	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
125	6	src/main/java/com/orb/battambang/checkupstation/EditHistoryController.java
113	9	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
29	8	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
137	8	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
29	7	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
41	26	src/main/resources/com/orb/battambang/checkup-menu.fxml
11	7	src/main/resources/com/orb/battambang/edit-history.fxml
45	30	src/main/resources/com/orb/battambang/hearing-test.fxml
33	29	src/main/resources/com/orb/battambang/height-and-weight.fxml
47	31	src/main/resources/com/orb/battambang/history.fxml
33	29	src/main/resources/com/orb/battambang/snellens-test.fxml
-	-	src/main/resources/databases/clinicdb.db
3	3	src/main/resources/com/orb/battambang/height-and-weight.fxml
1	1	src/main/resources/com/orb/battambang/snellens-test.fxml
-	-	src/main/resources/databases/clinicdb.db
-	-	src/main/resources/databases/clinicdb.db
10	5	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
10	4	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
12	12	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
10	4	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
98	6	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
3	3	src/main/resources/com/orb/battambang/height-and-weight.fxml
40	29	src/main/resources/com/orb/battambang/snellens-test.fxml
-	-	src/main/resources/databases/clinicdb.db
1	1	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
1	1	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
1	1	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
1	1	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
1	1	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
-	-	src/main/resources/databases/clinicdb.db
-	-	.executable/Milestone1/battambang-1.0-SNAPSHOT-shaded.jar
35	0	src/main/java/com/orb/battambang/checkupstation/BMICalculator.java
189	12	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
40	0	src/main/java/com/orb/battambang/checkupstation/EditHistoryController.java
150	0	src/main/java/com/orb/battambang/checkupstation/HearingTestController.java
293	0	src/main/java/com/orb/battambang/checkupstation/HeightAndWeightController.java
181	0	src/main/java/com/orb/battambang/checkupstation/HistoryController.java
150	0	src/main/java/com/orb/battambang/checkupstation/SnellensTestController.java
48	29	src/main/java/com/orb/battambang/login/LoginPageController.java
1	0	src/main/java/com/orb/battambang/login/NewUserController.java
97	13	src/main/resources/com/orb/battambang/checkup-menu.fxml
4	0	src/main/resources/com/orb/battambang/doctor-consult.fxml
32	0	src/main/resources/com/orb/battambang/edit-history.fxml
148	0	src/main/resources/com/orb/battambang/hearing-test.fxml
177	0	src/main/resources/com/orb/battambang/height-and-weight.fxml
157	0	src/main/resources/com/orb/battambang/history.fxml
152	0	src/main/resources/com/orb/battambang/snellens-test.fxml
-	-	src/main/resources/databases/clinicdb.db
-	-	.executable/Milestone1/battambang-1.0-SNAPSHOT-shaded.jar
189	12	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
48	29	src/main/java/com/orb/battambang/login/LoginPageController.java
1	0	src/main/java/com/orb/battambang/login/NewUserController.java
97	13	src/main/resources/com/orb/battambang/checkup-menu.fxml
4	0	src/main/resources/com/orb/battambang/doctor-consult.fxml
-	-	src/main/resources/databases/clinicdb.db
2	0	README.md
-	-	.executable/Milestone1/battambang-1.0-SNAPSHOT-shaded.jar
-	-	.executable/Milestone1/clinicdb.db
51	0	src/main/resources/com/orb/battambang/checkup-menu.fxml
23	0	src/main/resources/com/orb/battambang/doctor-consult.fxml
23	0	src/main/resources/com/orb/battambang/medicine-dispense.fxml
76	0	src/main/resources/com/orb/battambang/patient-registration.fxml
52	0	src/main/resources/com/orb/battambang/patient-search.fxml
1	1	STYLEGUIDE.md
142	0	STYLEGUIDE.md
1	1	src/main/java/com/orb/battambang/login/NewUserController.java
2	2	src/main/java/com/orb/battambang/reception/PatientRegistrationController.java
-	-	src/main/resources/databases/clinicdb.db
1	1	src/main/java/com/orb/battambang/MainApp.java
32	0	src/main/java/com/orb/battambang/checkupstation/CheckupMenuController.java
32	0	src/main/java/com/orb/battambang/doctor/DoctorConsultController.java
65	5	src/main/java/com/orb/battambang/login/LoginPageController.java
91	1	src/main/java/com/orb/battambang/login/NewUserController.java
32	0	src/main/java/com/orb/battambang/pharmacy/MedicineDispenseController.java
61	0	src/main/java/com/orb/battambang/reception/Patient.java
183	0	src/main/java/com/orb/battambang/reception/PatientRegistrationController.java
121	0	src/main/java/com/orb/battambang/reception/PatientSearchController.java
16	4	src/main/java/module-info.java
34	3	src/main/resources/com/orb/battambang/new-user.fxml
7	4	src/main/resources/com/orb/battambang/prompt-connect.fxml
-	-	src/main/resources/databases/clinicdb.db
0	0	testdb.db
38	0	.gitignore
3	0	.idea/.gitignore
7	0	.idea/encodings.xml
14	0	.idea/misc.xml
124	0	.idea/uiDesigner.xml
6	0	.idea/vcs.xml
-	-	.mvn/wrapper/maven-wrapper.jar
2	0	.mvn/wrapper/maven-wrapper.properties
0	0	TextField[id=pathTextField, styleClass=text-input text-field]
100	0	dependency-reduced-pom.xml
316	0	mvnw
188	0	mvnw.cmd
0	0	null
111	0	pom.xml
12	0	src/main/java/com/orb/battambang/Main.java
23	0	src/main/java/com/orb/battambang/MainApp.java
33	0	src/main/java/com/orb/battambang/connection/DatabaseConnection.java
122	0	src/main/java/com/orb/battambang/login/LoginPageController.java
4	0	src/main/java/com/orb/battambang/login/NewUserController.java
64	0	src/main/java/com/orb/battambang/login/PromptConnectController.java
23	0	src/main/java/com/orb/battambang/util/Labels.java
17	0	src/main/java/module-info.java
47	0	src/main/resources/com/orb/battambang/hello-view.fxml
47	0	src/main/resources/com/orb/battambang/login-page.fxml
8	0	src/main/resources/com/orb/battambang/new-user.fxml
25	0	src/main/resources/com/orb/battambang/prompt-connect.fxml
-	-	src/main/resources/databases/clinicdb.db
0	0	testdb.db
2	0	README.md
